name: Build and push to GCR Staging branch

on:
  push:
    branches: [ staging ]

jobs:

    deploy:
    
        name: Setup Gcloud Account
        runs-on: ubuntu-latest
        env:
          IMAGE_NAME: gcr.io/${{ secrets.GCR_DEV_PROJECT_ID }}/${{ secrets.GCR_DEV_APP_NAME }}-ver-{{ github.sha }}
        steps:

        - name: Check Out Repo 
          uses: actions/checkout@v2
        
        - name: Login
          uses: google-github-actions/setup-gcloud@master
          with:
            project_id: ${{ secrets.GCR_DEV_PROJECT_ID }}
            service_account_email: ${{ secrets.GCR_DEV_SERVICE_NAME }}
            service_account_key: ${{ secrets.GCR_DEV_KEY }}

        - name: Configure Docker
          run: gcloud auth configure-docker --quiet

        - name: Checkout repository
          uses: actions/checkout@v2

        - name: change python version
          run: sudo update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1

        - name: check python version
          run: sudo python --version

        - name: install venv
          run: sudo apt-get install -y python-venv
        
        - name: Install dep
          run: pip install virtualenv virtualenvwrapper        
        
        - name: run venv
          run: python -m venv env
          
        - name: run venv
          run: source env/bin/activate

        - name: Install req
          run: pip install -r django/requirements.txt       
        
        - name: Sync DB 
          run: python django/notejam/manage.py syncdb --noinput

        - name: Migrate
          run: python django/notejam/manage.py migrate --noinput 
        
        - name: Run Test
          run: python django/notejam/manage.py test
          
        - name: Build Docker image
          run: docker build . -t $IMAGE_NAME

        - name: Push Docker image
          run: docker push $IMAGE_NAME

   #     - name: Deploy Docker image
   #       run: gcloud run deploy ${{ secrets.PROJECT_ID }} --image $IMAGE_NAME --region us-central1 --platform managed
