name: Build Prod and push to GCR

on:
  push:
    branches: [ master ]

jobs:

    deploy:
    
        name: Setup Gcloud Account
        runs-on: ubuntu-latest
        env:
#          IMAGE_NAME: gcr.io/${{ secrets.PROJECT_ID }}/django-v${{ github.run_number }}
          IMAGE_NAME: gcr.io/cloud-run-project-327804/cloud-run-django/v${{ github.run_number }}
        steps:
        
        - name: Check Out Repo 
          uses: actions/checkout@v2
        
        - name: Login
          uses: google-github-actions/setup-gcloud@master
          with:
            project_id: ${{ secrets.PROJECT_ID }}
            service_account_email: ${{ secrets.SERVICE_NAME }}
            service_account_key: ${{ secrets.GCR_KEY }}

        - name: Configure Docker
          run: gcloud auth configure-docker --quiet

        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Build Docker image
          run: docker build . -t $IMAGE_NAME

        - name: Push Docker image
          run: docker push $IMAGE_NAME

        - name: Create New Instance Template
          run: gcloud compute instance-templates create-with-container instance-template-${{ github.run_number }} --tags=port8000 --container-image=$IMAGE_NAME:latest
        
        - name: Edit Instance Group with new Instance Template
          run: gcloud compute instance-groups managed set-instance-template instance-group-1 --zone=us-central1-a --template=instance-template-${{ github.run_number }}.

        - name: Recreate Instances
          run: gcloud compute --project "${{ secrets.PROJECT_ID }}" instance-groups managed recreate-instances  "instance-group-1" --zone "us-central1-a" --instances "instance-group-1-v57p"
          